PUB-2179 - Remove non-functional scrollbars
hmcts/pip-frontend pull request #1218
Opened 2024-02-28 14:23 UTC by NatashaAlker

Please remove this line and everything above and fill the following sections:

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-2179

### Change description

Remove all vertical scrollbars from list displays.
Remove non-functional horizontal scrollbars.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-02-29 10:08 UTC, ChrisS1512 requested changes
Theres one more list type that this needs sorting on which is the Primary Health List. 

Once that's done happy to approve

2024-03-01 09:10 UTC, ChrisS1512 approved these changes

2024-03-15 16:49 UTC, ChrisS1512 requested changes

2024-03-15 16:49 UTC, ChrisS1512 commented on src/main/views/care-standards-list.njk
> +      <table class="govuk-table" data-module="moj-sortable-table overflow-table">
I've found a bug which is causing the sorting on the table to no longer work. I believe this is due to the overflow-table property being against the data-module - I believe this needs to be under class.

2024-03-20 16:32 UTC, KianKwa approved these changes

2024-03-25 10:45 UTC, merged