PUB-733: Build Subscriptions Court Search Screen
hmcts/pip-frontend pull request #127
Opened 2021-10-28 10:02 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-733

### Change description ###
Added screen for Court Name search (4th selection on the add subscriptions page)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```
![initial](https://user-images.githubusercontent.com/25640912/139234238-a718a05a-1713-45e6-8939-6c971f95e33e.PNG)
![multiple-filters](https://user-images.githubusercontent.com/25640912/139234240-539857bc-680b-4846-8a9a-3047d8033223.PNG)
![with-filter](https://user-images.githubusercontent.com/25640912/139234241-b8d35cc9-d426-4004-9ea0-af51b6878ecd.PNG)

2021-11-01 09:31 UTC, kurt-uk requested changes

2021-11-01 09:31 UTC, kurt-uk commented on src/main/controllers/CourtNameSearchController.ts
> +    await courtService.fetchAllCourts().then((courts) => {
await is waiting for it all to be completed, `await` and `.then` are same outcomes to different types of sync so you should be able to just await and still check, we shouldnt combine async and sync, the only thing youre doing with then is passing the results as a variable to check when you can still do that with async

2021-11-01 09:31 UTC, kurt-uk commented on src/main/service/courtService.ts
> +    return alphabetOptions;
they all generate alphabet table of courts, the only difference is that one of them checks for empty hearings, but this one and the one that doesnt do that check could easily be combined

2021-11-01 09:31 UTC, kurt-uk commented on src/main/views/court-name-search.njk
> +{% from "govuk/components/table/macro.njk" import govukTable %}
i cant see the updated macro file in your commit

2021-11-02 15:14 UTC, kurt-uk requested changes

2021-11-02 16:30 UTC, kurt-uk approved these changes

2021-11-03 09:35 UTC, kurt-uk submitted a review, later dismissed

2021-11-03 09:58 UTC, johnoneill46 approved these changes

2021-11-03 10:13 UTC, johnoneill46 approved these changes

2021-11-03 12:50 UTC, kurt-uk approved these changes

2021-11-03 13:15 UTC, johnoneill46 approved these changes

2021-11-03 13:40 UTC, merged