PUB-2340-b
hmcts/pip-frontend pull request #1330
Opened 2024-08-19 10:14 UTC by NatashaAlker

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-2340

### Change description

Handle multiple session keys

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-08-20 08:17 UTC, ChrisS1512 requested changes
The README will need updating for this to add in the new SESSION_SECRET_V2

2024-08-23 10:17 UTC, ChrisS1512 submitted a review, later dismissed

2024-09-10 14:02 UTC, KianKwa approved these changes

2024-09-24 09:06 UTC, junaidiqbalmoj approved these changes

2024-09-24 09:09 UTC, merged