PUB-2554 Update region for ET lists' PDF
hmcts/pip-frontend pull request #1333
Opened 2024-08-27 11:29 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2554

### Change description ###

Update region for ET lists' style guide

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No

2024-08-28 09:01 UTC, ChrisS1512 approved these changes

2024-08-28 09:02 UTC, ChrisS1512 requested changes

2024-08-28 09:02 UTC, ChrisS1512 commented on src/main/controllers/style-guide/EtFortnightlyListController.ts
> +            const courtRegion = req.lng === 'cy' ? returnedCourt.welshRegion : returnedCourt.region;
Could we make the variable name here consistent between this controller and the daily (Happy with either one)

2024-08-28 09:56 UTC, ChrisS1512 submitted a review, later dismissed

2024-09-03 08:25 UTC, NatashaAlker approved these changes

2024-09-03 08:27 UTC, merged