PUB-1909 Modify System Audit Logs
hmcts/pip-frontend pull request #1385
Opened 2024-11-22 15:57 UTC by junaidiqbalmoj

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1909

### Change description

Modify System Audit Logs and add filters to the page.

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2024-12-03 09:15 UTC, KianKwa submitted a review, later dismissed

2024-12-10 10:37 UTC, ChrisS1512 requested changes

2024-12-10 10:37 UTC, ChrisS1512 commented on src/test/end-to-end/tests/system-admin/audit-log-test.ts
> +Scenario.skip(
Is the skip expected here?

2024-12-10 10:42 UTC, ashwini-mv commented on src/test/end-to-end/tests/system-admin/audit-log-test.ts
> +Scenario.skip(
No, I will remove that

2024-12-13 11:53 UTC, ChrisS1512 approved these changes

2024-12-18 11:02 UTC, merged