PUB-742 - Delete Subscription Flow
hmcts/pip-frontend pull request #184
Opened 2021-11-23 16:34 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-742

### Change description ###
- Update Unsubscribe links on the subscription management page to open unsubscribe page
- Add unsubscribe page with yes/no radio selections
- Add unsubscribe confirmation page when user successfully unsubscribes
- Add appropriate route, e2e, unit, and a11y tests
- Add additional unit tests to the subscriptionRequests to increase coverage

**NOTES:**
- All unsubscribe requests will fail as back end logic has not been developed yet
- Unsubscribe confirmation page has link to the your-account page, however that page does not exist at the moment. Pointing to non-existing page has been okayed by the BA (see ticket comments on JIRA)
- If user selects no on the unsubscribe selection, user is taken back to subscriptions management page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```
![unsubscribe](https://user-images.githubusercontent.com/25640912/143065199-77e15a5f-9315-4b9f-a56f-eda2f5d2fec8.PNG)
![confirmation](https://user-images.githubusercontent.com/25640912/143065191-e198f0cc-7aee-4757-93b9-1b2e2ec0681b.PNG)

2021-11-24 16:28 UTC, kurt-uk requested changes

2021-11-24 16:34 UTC, kurt-uk commented on src/main/resources/requests/subscriptionRequests.ts
> +import { dataManagementApi, subscriptionManagementApi } from './utils/axiosConfig';
resolving as its is misused by URN, will create tech debt ticket to remove this and put it into hearings requests

2021-11-25 16:56 UTC, commitBlob commented on src/main/controllers/UnsubscribeConfirmationController.ts
> +      const unsubscribeResponse = await subscriptionRequests.unsubscribe({...req.body, userId: req.user['id']});
should be done now

2021-11-26 12:41 UTC, alberto-hortiguela commented
/azp run

2021-12-17 11:02 UTC, furnivall approved these changes
Looks good man

2021-12-17 11:14 UTC, kurt-uk approved these changes

2021-12-21 12:05 UTC, ChrisS1512 approved these changes

2021-12-21 12:26 UTC, furnivall approved these changes
Looks good to me :)

2022-01-20 16:38 UTC, furnivall approved these changes

2022-01-21 10:29 UTC, marcogagliardi reviewed
👌🏽👌🏽

2022-01-21 11:51 UTC, marcogagliardi approved these changes
👌🏽

2022-01-24 14:10 UTC, merged