Pip-489 - Initialize e2e suite
hmcts/pip-frontend pull request #19
Opened 2021-07-02 13:00 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-489

### Change description ###
- Initialize e2e test with puppeteer
- add `yarn test:e2e` command to the scripts lists in `package.json`
- update README instructions to run e2e
- add 2 basic validation steps to verify start page is rendered and search option page is rendered after Start now button click

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-07-02 13:30 UTC, kurt-uk requested changes

2021-07-02 13:30 UTC, kurt-uk commented on src/test/e2e/e2e.ts
> +describe('End to end test', () => {
Can we try a Page Object Model approach to our e2e? i think using a common testing approach like that would be 1) easier to read 2) easier to maintain

2021-07-02 13:30 UTC, kurt-uk commented on src/test/e2e/e2e.ts
> +describe('End to end test', () => {
the describe should be the journey we are completing so something closer to `finding a court or tribunal listing`

2021-07-02 13:30 UTC, kurt-uk commented on src/test/e2e/e2e.ts
> +    browser = await puppeteer.launch({
all of this should belong in the config not the actual test file

2021-07-02 13:30 UTC, kurt-uk commented on src/test/e2e/e2e.ts
> +  test('should open main page with "Find a court or tribunal listing" title', async () => {
use `it` instead of `test`

2021-07-02 13:30 UTC, kurt-uk commented on src/test/e2e/e2e.ts
> +  test('should open main page with "Find a court or tribunal listing" title', async () => {
if we have pupeteer as async, should we try use lamda functions instead?

2021-07-02 13:54 UTC, kurt-uk commented on src/test/e2e/e2e.ts
> +describe('End to end test', () => {
> Can we try a Page Object Model approach to our e2e? i think using a common testing approach like that would be 1) easier to read 2) easier to maintain

or a Screenplay pattern? both would be useful

2021-07-05 15:08 UTC, kurt-uk commented on src/test/e2e/PageObjects/HomePage.ts
> +    expect(pageTitle).toBe('Find a court or tribunal listing');
we should have the tests on the test page, these page objects should return pages we are on and the evaluating be done on the object

2021-07-05 15:08 UTC, kurt-uk commented on src/test/e2e/PageObjects/HomePage.ts
> +import { Page } from 'puppeteer';
can we tag our page object files as `blahblah.po.ts` even though they're in the page object folder youve created, just nice to have them tagged as .po

2021-07-05 15:08 UTC, kurt-uk commented on src/test/e2e/PageObjects/HomePage.ts
> +    expect(radioElements.length).toBe(2);
this isnt the home page, if we return pages instead of expected it would make it easier to read and follow

2021-07-05 15:08 UTC, kurt-uk commented on src/test/e2e/Tests/e2e.ts
> +    headless: false, // set to false and uncomment slowMo and args to see tests in realtime
this is still a lot of config in the test suite, this needs moving to a puppeteer config file somewhere

2021-07-05 15:08 UTC, kurt-uk commented on src/test/e2e/Tests/e2e.ts
> +let page: Page;
if we return our own pages we can use those and the standard browser object in ours instead of the browsers new pages

2021-07-06 08:38 UTC, marcogagliardi approved these changes
👍

2021-07-06 15:21 UTC, kurt-uk approved these changes

2021-07-06 15:23 UTC, merged