PUB-875 - Filter hide functionality in small screen
hmcts/pip-frontend pull request #236
Opened 2022-01-28 12:42 UTC by marcogagliardi

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-875

### Change description ###
hide filter function in small screen
![Screenshot 2022-01-27 at 14 37 47](https://user-images.githubusercontent.com/25669179/151548977-4ea42abb-ba3a-49d5-b2a6-09c1ab38e4a4.png)
![Screenshot 2022-01-27 at 14 37 20](https://user-images.githubusercontent.com/25669179/151548991-a63ad89e-d217-4c98-88fd-2b95ca0b62d3.png)

2022-01-28 13:26 UTC, furnivall submitted a review, later dismissed
Looks good to me :)

2022-01-28 13:45 UTC, kurt-uk commented
> ### JIRA link
> https://tools.hmcts.net/jira/browse/PUB-875
> 
> ### Change description
> hide filter function in small screen ![Screenshot 2022-01-27 at 14 37 47](https://user-images.githubusercontent.com/25669179/151548977-4ea42abb-ba3a-49d5-b2a6-09c1ab38e4a4.png) ![Screenshot 2022-01-27 at 14 37 20](https://user-images.githubusercontent.com/25669179/151548991-a63ad89e-d217-4c98-88fd-2b95ca0b62d3.png)

is this how it actually looks or have you just not updated webpack?

2022-01-28 16:37 UTC, marcogagliardi commented
> > ### JIRA link
> > https://tools.hmcts.net/jira/browse/PUB-875
> > ### Change description
> > hide filter function in small screen ![Screenshot 2022-01-27 at 14 37 47](https://user-images.githubusercontent.com/25669179/151548977-4ea42abb-ba3a-49d5-b2a6-09c1ab38e4a4.png) ![Screenshot 2022-01-27 at 14 37 20](https://user-images.githubusercontent.com/25669179/151548991-a63ad89e-d217-4c98-88fd-2b95ca0b62d3.png)
> 
> is this how it actually looks or have you just not updated webpack?

it actually looks like that

2022-01-31 09:16 UTC, furnivall approved these changes
👍

2022-01-31 12:00 UTC, alberto-hortiguela approved these changes

2022-02-04 10:18 UTC, ChrisS1512 commented
Hey. The Hide / Show filters button doesn't appear to be showing for me.

![image](https://user-images.githubusercontent.com/87066931/152512113-df95a446-e33a-46ae-b190-d7ac0a86c9ef.png)

I feel like it might be something to do with this: <div class="moj-button-menu filters__innerButton" id="innerButton">, as anything I put in there doesn't appear.

2022-02-04 10:43 UTC, ChrisS1512 requested changes

2022-02-04 10:43 UTC, ChrisS1512 commented on src/test/e2e/tests/specs.test.ts
> +    it('should click on the first unsubscribe record', async () => {
Looks like there might be something strange with the subscriptions tests here. Don't believe these should have changed in this ticket so might be a merge conflict issue?

2022-02-04 16:29 UTC, marcogagliardi commented
> The Hide / Show filters button doesn't appear to be showing for me.
> 
> ![image](https://user-images.githubusercontent.com/87066931/152512113-df95a446-e33a-46ae-b190-d7ac0a86c9ef.png)
> 
> I feel like it might be something to do with this:
> 
> , as anything I put in there doesn't appear.

The hide/show button will be show only in mobile screen

2022-02-07 11:08 UTC, ChrisS1512 approved these changes

2022-02-07 11:33 UTC, alberto-hortiguela approved these changes

2022-02-08 12:49 UTC, alberto-hortiguela submitted a review, later dismissed

2022-02-08 13:50 UTC, ChrisS1512 submitted a review, later dismissed

2022-02-08 15:48 UTC, ChrisS1512 approved these changes

2022-02-14 10:32 UTC, merged