Pub-1030 - Connect Court A-Z page with Reference data endpoint
hmcts/pip-frontend pull request #269
Opened 2022-02-11 15:39 UTC by junaidiqbalmoj

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1030

### Change description ###

These changes will get the court data from data management api endpoint. All filters are being populated from reference data now.

NOTE: We need to remove some e2e tests now because we will keep getting reference data from the different source which cause total no of courts to be changed. Same for hearing and live case status, there is a possibility that we do not have hearing for a specific court which is defined in e2e tests.

![Image 11-02-2022 at 15 30](https://user-images.githubusercontent.com/84805836/153620279-483c9190-0401-480f-b2cc-85401c26383b.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-02-11 16:34 UTC, kurt-uk requested changes

2022-02-14 08:11 UTC, marcogagliardi approved these changes
👌🏽

2022-02-14 09:52 UTC, junaidiqbalmoj commented on src/main/controllers/AlphabeticalSearchController.ts
> +    const alphabetisedList = await courtService.generateFilteredAlphabetisedCourtList(filters['Region'], filters['Jurisdiction']);
No, this is how it was build before and I did not change that logic. For filters, we are calling the API again, and it returns us the filtered data. We are not filtering data inside frontend.

2022-02-14 09:52 UTC, junaidiqbalmoj commented on src/main/controllers/CourtNameSearchController.ts
> +    const alphabetisedList = await courtService.generateFilteredAlphabetisedCourtList(filters['Region'], filters['Jurisdiction']);
No, this is how it was build before and I did not change that logic. For filters, we are calling the API again, and it returns us the filtered data. We are not filtering data inside frontend.

2022-02-14 12:47 UTC, kurt-uk approved these changes

2022-02-14 13:25 UTC, marcogagliardi submitted a review, later dismissed
👌🏽

2022-02-16 11:38 UTC, kurt-uk approved these changes

2022-02-21 13:01 UTC, commitBlob approved these changes

2022-02-21 13:15 UTC, merged