Pub 1037 list manual remove
hmcts/pip-frontend pull request #298
Opened 2022-03-03 15:22 UTC by commitBlob

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-03 17:01 UTC, kurt-uk requested changes

2022-03-03 17:01 UTC, kurt-uk commented on src/test/unit/views/remove-list-confirmation.test.ts
> +    it('should display error messages in th the summary', () => {
```suggestion
    it('should display error messages in the summary', () => {
```

2022-03-09 16:24 UTC, kurt-uk approved these changes
nice work!

2022-03-15 15:02 UTC, furnivall approved these changes
looks good 👍

2022-03-15 16:01 UTC, furnivall submitted a review, later dismissed
👍

2022-03-21 10:18 UTC, kurt-uk approved these changes

2022-03-22 14:47 UTC, alberto-hortiguela submitted a review, later dismissed

2022-04-07 08:20 UTC, ChrisS1512 approved these changes

2022-04-07 08:23 UTC, merged