Pip 511 data mock parse
hmcts/pip-frontend pull request #31
Opened 2021-07-23 15:24 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-511

### Change description ###
Add mocked data and retrieve it in JSON format. Once back end APIs are set up mocked requests need to be updated

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-07-23 16:05 UTC, johnoneill46 approved these changes

2021-07-26 08:39 UTC, kurt-uk requested changes

2021-07-26 08:39 UTC, kurt-uk commented on src/main/routes/api/requests.ts
> +  app.get('/api/court/:courtId', (req, res) => {
this is one very long function thats doing multiple things, can we split it so its single responsibility with multiple method calls like `getCourts` or something?

2021-07-26 08:39 UTC, kurt-uk commented on src/test/unit/routes/api/requests.ts
> +  describe('on GET', () => {
doesnt look like you need the nested describe

2021-07-26 08:39 UTC, kurt-uk commented on src/test/unit/routes/api/requests.ts
> +  describe('on GET', () => {
again no nested describe needed, theyre for splitting sub tests

2021-07-27 09:52 UTC, johnoneill46 approved these changes

2021-07-29 08:17 UTC, kurt-uk approved these changes

2021-07-29 08:25 UTC, merged