Pub 1182 split date inputs
hmcts/pip-frontend pull request #316
Opened 2022-03-18 11:42 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-1182

### Change description ###
Split display date files into own rows
Wrap page in parent box and include super call (futureproofing for Kurt's back to top implementation)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```
![split](https://user-images.githubusercontent.com/25640912/158997088-2a3797ca-383a-4890-8b5c-207e5abbf2a1.PNG)

2022-03-21 12:50 UTC, alberto-hortiguela approved these changes

2022-03-22 10:57 UTC, ChrisS1512 approved these changes

2022-03-23 09:03 UTC, merged

2022-03-23 09:15 UTC, ChrisS1512 requested changes

2022-03-23 09:15 UTC, ChrisS1512 commented on src/test/unit/views/manual-upload.test.ts
> +      expect(displayDateFrom.innerHTML).contains(expectedDisplayDateFrom, 'Could not find inset content date question');
I believe the messages on line 104 / 105 should be updated from content date to display from / display to