PUB-1174 - Change Page Titles
hmcts/pip-frontend pull request #321
Opened 2022-03-22 11:29 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-1174

### Change description ###
Add titles to pages and add unit tests to check whether correct titles are set

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-22 12:21 UTC, alberto-hortiguela approved these changes

2022-03-23 09:28 UTC, ChrisS1512 requested changes

2022-03-23 09:49 UTC, commitBlob commented on src/test/a11y/a11y.ts
> +  app.request['cookies'] = {'formCookie': JSON.stringify({'foo': 'blah'})};
true, should be removed
it was merge in merge conflicts

2022-03-23 09:56 UTC, ChrisS1512 approved these changes

2022-03-23 10:14 UTC, alberto-hortiguela approved these changes

2022-03-23 10:15 UTC, alberto-hortiguela commented on src/test/a11y/a11y.ts
> +  app.request['cookies'] = {'formCookie': JSON.stringify({'foo': 'blah'})};
@ChrisS1512 needs approving finish with the PR

2022-03-25 08:27 UTC, merged