PUB-1211 Daily Cause List Version2
hmcts/pip-frontend pull request #341
Opened 2022-04-05 13:41 UTC by junaidiqbalmoj

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1211

### Change description ###

Update the frontend template for Daily Cause List Version 2 Schema
Upgraded govuk frontend to match the new component designs requested for Accordion

![Image 05-04-2022 at 14 40](https://user-images.githubusercontent.com/84805836/161766963-d1331add-ce7c-409e-9ea7-8f2776d1f29e.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-04-05 16:12 UTC, ChrisS1512 requested changes
Looks good! Can we double check we have an E2E test for this page, and if not add on in? Other than that, looks good

2022-04-06 08:51 UTC, junaidiqbalmoj reviewed
As discussed, comment has been resolved :)

2022-04-06 12:46 UTC, ChrisS1512 approved these changes

2022-04-06 12:48 UTC, furnivall submitted a review, later dismissed
LGTM

2022-04-12 16:20 UTC, ChrisS1512 approved these changes

2022-04-22 10:18 UTC, ChrisS1512 approved these changes

2022-04-22 10:21 UTC, furnivall approved these changes

2022-04-25 17:46 UTC, merged