pub-508 - Added search results list
hmcts/pip-frontend pull request #36
Opened 2021-08-04 13:37 UTC by kurt-uk

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-508

### Change description ###
## Added
new nunjucks file to display search results
controller for search results
service directory that contains a input filter to check inputs for searching against values in the json data

tests 

## Changed/updated
updated json mock data for courts to include `location` and `jurisdiction` as values that can searched against
updated main.scss to add class that allows table to be used without the cell lines
updated and extended gov class to make the first and last cell display lines

Added new nunjucks file for displaying the search results, added to the main.scss to modify table cell classes for first and last to display lines and created new class to remove lines for others,

### NOTE
not linked yet, blocked through 506

## screenshot
<img width="959" alt="Screenshot 2021-08-04 at 14 30 44" src="https://user-images.githubusercontent.com/26488566/128189579-0e424750-62a5-4fa0-9713-89ae082d2749.png">

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-08-04 16:15 UTC, ChrisS1512 requested changes

2021-08-04 16:15 UTC, ChrisS1512 commented on src/main/views/search-results.njk
> +      <th scope="col" class="govuk-table__header--numeric">Number of hearings</th>
I'm getting an issue where the header line / border-bottom of the numeric column doesn't appear.

Looks like govuk-table__header--numeric only does the right align - so also need the govuk-table__header class as well

2021-08-04 16:15 UTC, ChrisS1512 commented on src/main/views/search-results.njk
> +        <th scope="row" class="govuk-table__cell--no-line govuk-link"><a href="/hearing-list?courtId={{ result.courtId }}">{{ result.name }}</a></th>
I think the anchor tag on this line should use the link styling class on here: https://design-system.service.gov.uk/styles/typography/

2021-08-04 16:15 UTC, ChrisS1512 commented on src/main/views/search-results.njk
> +        <th scope="row" class="govuk-table__cell--no-line govuk-link"><a href="/hearing-list?courtId={{ result.courtId }}">{{ result.name }}</a></th>
The content of the first column seems to be centre aligned on mine, rather than left aligned (think it could be to do with the table__cell class)

2021-08-04 16:15 UTC, ChrisS1512 commented on src/main/views/search-results.njk
> +      </tr>
It looks like the bottom of the table is missing an end line

I think this could be because my search only has one result in it rather than > 1

2021-08-05 10:16 UTC, ChrisS1512 approved these changes

2021-08-05 10:23 UTC, johnoneill46 approved these changes

2021-08-05 10:33 UTC, merged