PUB-1208 - beta heading added to interstitial and template
hmcts/pip-frontend pull request #361
Opened 2022-04-25 10:26 UTC by furnivall

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-26 12:38 UTC, furnivall commented on src/main/views/interstitial.njk
> +  }) }}
yeah fair point, can do :)

2022-04-26 15:24 UTC, joshblackmoor approved these changes
LGTM :)

2022-04-26 16:03 UTC, ChrisS1512 submitted a review, later dismissed

2022-04-27 13:46 UTC, ChrisS1512 approved these changes

2022-04-27 13:49 UTC, joshblackmoor submitted a review, later dismissed

2022-04-27 15:54 UTC, kurt-uk requested changes

2022-04-27 15:54 UTC, kurt-uk commented on src/main/views/interstitial.njk
> +  }) }}
if you have this in the template, why include it here also? this page extends the template

2022-04-28 09:09 UTC, kurt-uk approved these changes

2022-04-29 15:14 UTC, ChrisS1512 approved these changes

2022-04-29 16:01 UTC, merged