PUB-1172 Admin upload screen help text
hmcts/pip-frontend pull request #364
Opened 2022-04-25 13:46 UTC by joshblackmoor

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1172

### Change description ###

Added help text to the manual upload page & split the page in to thirds, existing form is 2/3 and new help section 1/3. 

![Screenshot 2022-04-25 at 14 46 01](https://user-images.githubusercontent.com/23316525/165101958-41999476-9240-4c90-901b-79d798af4580.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-04-27 11:32 UTC, ChrisS1512 requested changes

2022-04-27 11:32 UTC, ChrisS1512 commented on src/main/views/manual-upload.njk
> +        <h3 class="govuk-heading-s">Hearing lists</h3>
Rather than the raw text being in here, we should put the text in the resources/locales/en/manual-upload.json and reference in from there :)

2022-04-27 12:45 UTC, ChrisS1512 approved these changes

2022-04-27 13:02 UTC, furnivall approved these changes
Looks good to me! 👍

2022-04-28 12:22 UTC, ChrisS1512 submitted a review, later dismissed

2022-04-28 12:25 UTC, furnivall approved these changes

2022-04-29 11:07 UTC, ChrisS1512 approved these changes

2022-04-29 13:09 UTC, furnivall approved these changes
LGTM :)

2022-04-29 13:09 UTC, merged