unit tests sorted
hmcts/pip-frontend pull request #365
Opened 2022-04-28 10:54 UTC by furnivall

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-1102

### Change description ###
Added some unit tests. There is already an existing e2e test which is locked behind an environment variable to only apply when an sjp list exists in staging, so no need to add another.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-04-28 11:02 UTC, joshblackmoor submitted a review, later dismissed

2022-04-28 11:08 UTC, ChrisS1512 requested changes

2022-04-28 11:08 UTC, ChrisS1512 commented on src/test/unit/mocks/newSJPMocks.json
> +{"document": {"publicationDate": "25th March 2022","version": "<O8|jZo>","documentName": "Uh"},"courtLists": [{"courtHouse": {"courtRoom": [{"session": [{"sittings": [{"hearing":[{"party":[{"partyRol
Only minor, however could we change the name of this file to be something more descriptive (list type would work)

2022-04-28 12:18 UTC, ChrisS1512 submitted a review, later dismissed

2022-04-28 12:19 UTC, joshblackmoor approved these changes

2022-04-29 08:32 UTC, ChrisS1512 approved these changes

2022-04-29 08:33 UTC, joshblackmoor approved these changes

2022-04-29 13:56 UTC, merged