PUB-1050 Admin Login Page
hmcts/pip-frontend pull request #376
Opened 2022-05-06 13:55 UTC by junaidiqbalmoj

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1050

### Change description ###

Create Admin login screen. Made changes so that only admin can access the admin screen.

![Image 06-05-2022 at 14 52](https://user-images.githubusercontent.com/84805836/167147108-b2ba8af2-8ff3-470a-9695-dd3ca012f944.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-05-09 10:00 UTC, junaidiqbalmoj reviewed
Fix the existing tests and add unit tests.

2022-05-09 12:16 UTC, furnivall submitted a review, later dismissed
LGTM

2022-05-09 13:47 UTC, ChrisS1512 requested changes

2022-05-09 14:04 UTC, ChrisS1512 approved these changes

2022-05-09 14:05 UTC, junaidiqbalmoj commented on src/main/authentication/adminAuthentication.ts
> +      const userInfo = req.user['_json'];
Double check again, user object does not contain extension_UserRole attribute in it. Custom user attributes like extension_UserRole, family_name etc are coming in _json.

2022-05-16 09:43 UTC, ChrisS1512 approved these changes

2022-05-16 09:55 UTC, furnivall approved these changes
LGTM :)

2022-05-18 14:45 UTC, kurt-uk approved these changes

2022-05-18 14:47 UTC, merged