Pub 1275 a z changes
hmcts/pip-frontend pull request #392
Opened 2022-05-16 14:20 UTC by kurt-uk

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-1275

### Change description ###
branched from 1264

Updated a-z pages on public and subscribe journey, removed SJP hack and all locations display under the same collection. headings removed.

also applied filter heading change on subscribe a-z page

## screenshots
![Screenshot 2022-05-16 at 15 19 42](https://user-images.githubusercontent.com/26488566/168614148-ee6579af-f717-47d0-a8dc-b735a5be4c7d.png)
![Screenshot 2022-05-16 at 15 19 58](https://user-images.githubusercontent.com/26488566/168614205-3c06e0ee-ca66-44e1-91ba-af70c01ab252.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-16 15:49 UTC, joshblackmoor submitted a review, later dismissed

2022-05-16 16:56 UTC, ChrisS1512 requested changes
Looks good! Unit tests failed but I think it could just be the environment. Could you have a look?

2022-05-17 09:37 UTC, kurt-uk commented
> Looks good! Unit tests failed but I think it could just be the environment. Could you have a look?

@ChrisS1512 This build wont pass e2e until BE is merged as its using new api of `/location...` rather than courts

2022-05-17 09:55 UTC, ChrisS1512 submitted a review, later dismissed

2022-05-17 09:57 UTC, kurt-uk commented
Holding off merging until all BE related have been merged, then e2e need looking at, but moving across to allow testing to progress locally

2022-05-27 09:37 UTC, joshblackmoor approved these changes

2022-05-27 11:10 UTC, merged