PUB 1290 cookies page updates
hmcts/pip-frontend pull request #425
Opened 2022-06-10 10:29 UTC by joshblackmoor

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1290

### Change description ###

- Updated cookies page with new wording
- Added welsh version of the cookie page
- Added form to enable/disable some cookies, this form doesn't work currently as there are no cookies to use with it. This will need updating in the future

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-13 08:38 UTC, ChrisS1512 requested changes

2022-06-13 08:38 UTC, ChrisS1512 commented on src/main/resources/locales/cy/cookie-policy.json
> +{
Not specific to this file, however alongside the below we should also ensure that the cookies are disabled when the user declines them.

I believe theres code elseware in this repo that we can plugin to do this.

2022-06-13 09:36 UTC, kurt-uk commented
cant see where the logic is that uses the functionality of actually disabling or enabling depending on the toggles; see cookie-preferences.js

2022-06-14 08:20 UTC, ChrisS1512 requested changes
Currently getting a sonarqube failure on the build. Once sorted I'll give this a test

2022-06-15 14:54 UTC, ChrisS1512 commented
Just trying this out now via the DEV pod and seems to be keeping the cookies. Would you be able to try it out to see if you get the same result?

2022-06-17 12:32 UTC, furnivall submitted a review, later dismissed
Really great work guys - <3

2022-06-22 10:41 UTC, ChrisS1512 submitted a review, later dismissed

2022-06-27 13:09 UTC, ChrisS1512 approved these changes

2022-06-27 13:10 UTC, junaidiqbalmoj approved these changes

2022-06-27 13:11 UTC, merged