PUB-1341 - Added logging for approval/rejection
hmcts/pip-frontend pull request #436
Opened 2022-06-22 15:04 UTC by ChrisS1512

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1341

### Change description ###

Added logging for approval / rejection

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-23 07:36 UTC, joshblackmoor approved these changes

2022-06-23 09:46 UTC, kurt-uk requested changes

2022-06-28 13:39 UTC, ChrisS1512 commented on src/main/service/mediaAccountApplicationService.ts
> +      logger.info('Admin ' + adminEmail + ' has approved media account ' + mediaApplication.id);
I've updated this now and created a log helper similar to the backend

2022-06-28 13:41 UTC, kurt-uk approved these changes
looks good! asking @chris-pateman to apprive on my behalf

2022-06-28 14:04 UTC, chris-pateman approved these changes
approved on behalf of kurt

2022-06-28 14:33 UTC, joshblackmoor approved these changes

2022-07-04 13:02 UTC, merged