PUB-1213 to PUB-1217 AAD admin and IDAM user sign-in notification
hmcts/pip-frontend pull request #505
Opened 2022-08-17 13:43 UTC by KianKwa

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1213
https://tools.hmcts.net/jira/browse/PUB-1214
https://tools.hmcts.net/jira/browse/PUB-1215
https://tools.hmcts.net/jira/browse/PUB-1216
https://tools.hmcts.net/jira/browse/PUB-1217

### Change description ###

After the admin user sign in, pass the user sign-in date to the account management api so the last signed-in date can be set for that account. This is then used for sending sign-in notification e-mail and deleting user account.  

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-18 12:24 UTC, ChrisS1512 requested changes
Just needs conflict sorting here :)

2022-08-19 11:56 UTC, joshblackmoor submitted a review, later dismissed

2022-08-19 12:23 UTC, ChrisS1512 approved these changes

2022-08-24 10:56 UTC, joshblackmoor submitted a review, later dismissed

2022-08-24 10:57 UTC, furnivall approved these changes

2022-08-24 10:59 UTC, ChrisS1512 submitted a review, later dismissed

2022-09-13 09:19 UTC, joshblackmoor approved these changes

2022-09-13 09:20 UTC, ChrisS1512 approved these changes

2022-09-13 09:40 UTC, merged