PUB-1570 Media user download SJP public and press list
hmcts/pip-frontend pull request #582
Opened 2022-11-21 18:40 UTC by KianKwa

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1570

### Change description ###

Add option to download SJP public list and SJP press list for media users

![image](https://user-images.githubusercontent.com/80688761/203133953-0720ebe4-e9c9-44e5-9f97-86166eb63ea2.png)

![image](https://user-images.githubusercontent.com/80688761/203134015-b001c4dd-20e2-4770-95bc-e4bc8eba9444.png)

![image](https://user-images.githubusercontent.com/80688761/203134137-318ba863-7c21-484f-b8fc-6afe6e1c9dc5.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-11-22 17:11 UTC, ChrisS1512 requested changes

2022-11-22 17:11 UTC, ChrisS1512 commented on src/test/unit/views/list-download-files.test.ts
> +import {app} from '../../../main/app';
Not this file, but I think we should add SJP view tests too for the new functionality

2022-11-23 16:52 UTC, joshblackmoor submitted a review, later dismissed

2022-11-23 16:59 UTC, ChrisS1512 submitted a review, later dismissed

2022-11-29 15:11 UTC, furnivall approved these changes

2022-11-29 15:11 UTC, merged