pip-6959 - Created api util - use of the api to gather data for each …
hmcts/pip-frontend pull request #59
Opened 2021-09-06 08:31 UTC by marcogagliardi

…controllers and actions - removed mock data - removed logic of filtering and ordering data - added mock data for testing - refactor tests

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-659

### Change description ###
removed mocks data - added api request util - refactor tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-09-06 11:23 UTC, commitBlob reviewed
There are loads of linting errors which will cause build process to fail as it is part of the build step

2021-09-06 11:23 UTC, commitBlob commented on src/main/controllers/SearchController.ts
> +      //res.redirect(`search-results?search-input=${searchInput}`);
can we remove commented out lines please

2021-09-06 11:23 UTC, commitBlob commented on src/main/modules/awilix/index.ts
> +    console.log(Axios);
remove these console logs please

2021-09-06 11:23 UTC, commitBlob commented on src/main/utils/PipApi.ts
> +    private readonly axios: AxiosInstance
lint - error - comma dangle

2021-09-06 11:23 UTC, commitBlob commented on src/main/utils/PipApi.ts
> +      .get(`/court/${courtId}`, {  headers: {'Accept-Language': "en"}})
lint - error - single quotes please

2021-09-06 11:23 UTC, commitBlob commented on src/main/utils/PipApi.ts
> +    console.log(this.axios)
drop this console log please

2021-09-06 11:23 UTC, commitBlob commented on src/test/unit/actions/courtActions/court.test.ts
> +    return courtActions.getCourtsList().then(data => {
lint - error - indentation

2021-09-06 11:23 UTC, commitBlob commented on src/test/unit/service/inputFilterService.test.ts
> +  "courtId": 3,
lint - error - single quotes

2021-09-06 11:23 UTC, commitBlob commented on src/test/unit/service/inputFilterService.test.ts
> +    expect(inputService.findCourts(validSearchInputName, validCheckAgainst, courtsData)).to.deep.equal(expectedResultFromName, 'Result did not match expected');
can we break these lines into couple of rows please?
Don't really want to scroll sideways to read whole line

2021-09-06 11:23 UTC, commitBlob commented on src/test/unit/views/alphabetical-search.ts
> +    return {
lint - error - indent

2021-09-06 11:23 UTC, commitBlob commented on src/test/unit/views/alphabetical-search.ts
> +          get: function(a, b) {return new Promise((resolve) => resolve({data: hearingsData}))}}},
a, b - unused parameters
lint - error - missing semicolon

2021-09-06 11:24 UTC, commitBlob commented
Conflicting files
src/test/unit/controllers/SearchController.test.ts

2021-09-06 11:58 UTC, marcogagliardi commented on src/main/controllers/AlphabeticalSearchController.ts
> +import {PipApi} from "../utils/PipApi";
done

2021-09-06 11:59 UTC, marcogagliardi commented on src/main/controllers/AlphabeticalSearchController.ts
> +let _api:PipApi;
done

2021-09-15 15:38 UTC, kurt-uk requested changes

2021-09-15 16:26 UTC, kurt-uk requested changes

2021-09-15 16:26 UTC, kurt-uk commented on src/main/controllers/LocalApiController.ts
> +import { Request, Response } from 'express';
didnt you just split all this out? why add it back in?

2021-09-16 08:14 UTC, commitBlob reviewed
Why do we have so many blank lines across the files? 1 blank line is okay but 2-3 for separation is unnecessary in my opinion

2021-09-16 08:14 UTC, commitBlob commented on package.json
> +    "axios": "^0.21.1",
might as well try to bump axios to version 0.21.4 and confirm all is working fine.
There is dependabot PR referring to this update with 97% compatibility.
There doesn't seem to be any major changes or breaking changes, however we should still check that we don't have any edge cases
https://github.com/hmcts/pip-frontend/pull/67

2021-09-16 08:14 UTC, commitBlob commented on src/main/models/court.ts
> +export class Court {
shouldn't this be interface rather than a class?
we are getting rid of puppeteer so you might need to look into alternative

2021-09-16 08:14 UTC, commitBlob commented on src/main/routes/routes.ts
> +  app.get('/courtlistall', app.locals.container.cradle.localApiController.allCourtList);
can we add /api prefix to the route to make it more obvious

2021-09-16 08:14 UTC, commitBlob commented on src/test/a11y/a11y.ts
> +    if (route != '/courtlistall' && route != '/courtlist/:input' && route != '/hearings/:courtId') {
if we add api prefix to the route as I mentioned above we can just ignore all routes on /api/* path rather than having to define each

2021-09-17 07:54 UTC, commitBlob approved these changes

2021-09-20 09:45 UTC, ChrisS1512 reviewed
This could just be the the test data, however when I'm going through the searching for a court by name page, I end up getting a slightly broken screen below.

Is this just due to the test data? (e.g a name appearing in the list that has no corresponding hearings)

![Screenshot 2021-09-20 at 10 40 35](https://user-images.githubusercontent.com/87066931/133982973-309b33b5-e189-4af9-8090-e627bd0748ef.png)

2021-09-20 09:50 UTC, ChrisS1512 requested changes
Once this is merged I believe our sandbox environment will display no results - until a link up between business rules + the frontend is done.

Has there already been any discussion on this / whether it's OK? If not I think it's worth raising

2021-09-27 14:19 UTC, ChrisS1512 approved these changes

2021-09-27 15:04 UTC, merged