PUB-1533 - Cancelled password reset
hmcts/pip-frontend pull request #609
Opened 2022-11-23 12:44 UTC by ChrisS1512

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1533

### Change description ###

Added cancelled password reset page

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/87066931/203549898-b9f2781f-727f-4341-9070-a9f114768f82.png">

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-11-23 17:07 UTC, joshblackmoor requested changes
Code looks good. I think we need to update the password reset URLs in flux config that we send with notify to reflect this new change.

2022-11-24 09:54 UTC, ChrisS1512 commented
> Code looks good. I think we need to update the password reset URLs in flux config that we send with notify to reflect this new change.

Good spot! I've added PR's for sds flux + pub services

2022-11-24 10:33 UTC, KianKwa approved these changes

2022-11-24 11:17 UTC, joshblackmoor approved these changes

2022-12-01 12:38 UTC, joshblackmoor approved these changes

2022-12-01 13:12 UTC, KianKwa approved these changes

2022-12-01 13:44 UTC, merged