Pub 695
hmcts/pip-frontend pull request #62
Opened 2021-09-07 10:03 UTC by Matthew-Summerbell

### JIRA link ###

### Change description ###
Replaced E2E tests with webdriver io

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-09-07 16:03 UTC, kurt-uk approved these changes

2021-09-10 08:16 UTC, commitBlob approved these changes

2021-09-17 15:01 UTC, commitBlob approved these changes
👍

2021-09-20 09:05 UTC, kurt-uk requested changes
with localhost hard coded?

2021-09-20 09:50 UTC, kurt-uk approved these changes

2021-09-20 09:52 UTC, merged