PUB-1694 Table sorting for list content
hmcts/pip-frontend pull request #655
Opened 2022-12-12 14:55 UTC by KianKwa

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1694

### Change description ###

Add table sorting for list content. This is implemented for all lists expect:
- SJP press list
- Magistrates standard list

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-13 14:13 UTC, joshblackmoor requested changes
Each accordion now has this been appearing and clicking the link to open/close is no longer working
![Screenshot 2022-12-13 at 14 12 02](https://user-images.githubusercontent.com/23316525/207356149-92b8c320-ab1b-4b97-ae01-1a86766dcbd9.png)

2022-12-14 18:37 UTC, joshblackmoor submitted a review, later dismissed

2022-12-15 10:36 UTC, ChrisS1512 submitted a review, later dismissed

2022-12-16 14:14 UTC, ChrisS1512 approved these changes

2022-12-16 15:57 UTC, junaidiqbalmoj approved these changes

2022-12-16 15:59 UTC, merged