PUB-1665 Refactor code for all artefacts per location endpoint
hmcts/pip-frontend pull request #667
Opened 2022-12-20 16:22 UTC by junaidiqbalmoj

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1665

### Change description ###

This endpoint is returning Map which will have location id and total no of artefacts for that location and display on blob explorer page.

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-12-22 10:32 UTC, joshblackmoor requested changes
Looks good. Will approve once build passes, think has some lint issues currently

2022-12-22 10:54 UTC, KianKwa approved these changes

2022-12-22 10:55 UTC, joshblackmoor submitted a review, later dismissed

2023-01-10 13:11 UTC, joshblackmoor submitted a review, later dismissed

2023-02-21 09:49 UTC, ChrisS1512 approved these changes

2023-02-21 09:49 UTC, joshblackmoor approved these changes

2023-02-21 09:56 UTC, merged