pub-514: Add Live Case Status Updates Screens
hmcts/pip-frontend pull request #70
Opened 2021-09-15 08:30 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/PUB-514

### Change description ###
- Add screens for live case status update screens and appropriate tests.
- Update jurisdictions on mock data to better reflect court names
- Add todo notes which will need to be updated once PR  for [pub 695 ](https://github.com/hmcts/pip-frontend/pull/62) is merged in

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-09-15 09:10 UTC, commitBlob commented
![Capture](https://user-images.githubusercontent.com/25640912/133405449-f6a7ed8c-5859-47d8-b4af-58b668a39918.PNG)
![Capture2](https://user-images.githubusercontent.com/25640912/133405452-bbd51dda-bcab-4e8e-b1f4-53626c1977d1.PNG)
![Capture3](https://user-images.githubusercontent.com/25640912/133405454-d2231b12-770e-4012-9517-e5a811a27611.PNG)

2021-09-16 08:44 UTC, johnoneill46 approved these changes

2021-09-16 10:48 UTC, kurt-uk requested changes

2021-09-16 10:48 UTC, kurt-uk commented on src/test/e2e/PageObjects/LiveHearings.po.ts
> +    return new HearingListPo(page);
this can return nothing for now until we play 720 which would be the correct screen

2021-09-16 10:48 UTC, kurt-uk commented on src/test/e2e/Tests/e2e.test.ts
> +  describe('Following the \'live hearing updates\' path', () => {
```suggestion
  describe('Following the \'live case status updates\' path', () => {
```

2021-09-17 08:44 UTC, kurt-uk requested changes

2021-09-17 08:44 UTC, kurt-uk commented on src/main/controllers/LiveCaseStatusUpdatesController.ts
> +    const courtsList = new CourtActions().getCourtsList();
can this exist in the class of the line below since we dont actually need this in here?

2021-09-17 08:44 UTC, kurt-uk commented on src/main/service/courtService.ts
> +  public generateCrownCourtArray(courtsList): object {
can we split this into a method that creates a 2 dimensional array for alphabet and courts and one that limits it to the crown court? that way we can reuse this method on this journey and the one on listings for the other alphabet page

2021-09-17 08:44 UTC, kurt-uk commented on src/main/views/live-case.njk
> +    {{ "Live Hearings Courts List" | safe }}
```suggestion
    {{ "Live Case Status Updates" | safe }}

```

2021-09-17 08:44 UTC, kurt-uk commented on src/test/unit/controllers/LiveCaseStatusUpdatesController.test.ts
> +describe('Live Hearings Controller', () => {
```suggestion
describe('Live Case Status Updates Controller', () => {
```

2021-09-17 08:44 UTC, kurt-uk commented on src/test/unit/controllers/LiveCaseStatusUpdatesController.test.ts
> +      set: () => {return '';},
you dont use a set?

2021-09-17 08:44 UTC, kurt-uk commented on src/test/unit/controllers/LiveCaseStatusUpdatesController.test.ts
> +    const liveHearingsController = new LiveCaseStatusUpdatesController();
```suggestion
    const liveCaseStatusUpdatesController = new LiveCaseStatusUpdatesController();
```

2021-09-17 08:44 UTC, kurt-uk commented on src/test/unit/service/courtService.test.ts
> +    console.log(crownCourtsArray);
left a log in

2021-09-17 12:31 UTC, kurt-uk approved these changes

2021-09-17 14:55 UTC, kurt-uk commented on src/main/controllers/LiveCaseStatusUpdatesController.ts
> +import { Request, Response } from 'express';
actually looking at the other PR this is actually LiveCaseCourtSearchController

2021-09-17 14:57 UTC, kurt-uk commented on src/main/views/live-case.njk
> +{% from "govuk/components/table/macro.njk" import govukTable as 'govukTable' %}
this file would be renamed to `live-case-court-search` or `live-case-alphabet-search`

2021-09-17 14:59 UTC, kurt-uk requested changes

2021-09-17 14:59 UTC, kurt-uk commented on src/test/e2e/PageObjects/LiveCase.po.ts
> +// TODO: needs refactoring when PUB-695 gets merged in
this file would rename too

2021-09-20 08:29 UTC, kurt-uk commented on src/test/unit/controllers/LiveCaseStatusUpdatesController.test.ts
> +import sinon from 'sinon';
this file name needs updating too

2021-09-20 08:30 UTC, kurt-uk commented on src/test/unit/controllers/LiveCaseStatusUpdatesController.test.ts
> +describe('Live Case Status Controller', () => {
```suggestion
describe('Live Case Court Search Controller', () => {
```

2021-09-20 09:00 UTC, kurt-uk approved these changes

2021-09-21 08:37 UTC, kurt-uk approved these changes

2021-09-22 15:13 UTC, merged