PUB-1725 Added changes to helmet config
hmcts/pip-frontend pull request #721
Opened 2023-01-20 10:53 UTC by joshblackmoor

### JIRA link ###

https://tools.hmcts.net/jira/browse/PUB-1725

### Change description ###

Updated the helmet config for CSP errors.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-25 12:26 UTC, ChrisS1512 requested changes
Just testing on the PR, I'm still getting a script error when it tries to connect to google analytics. Would you be able to have another look? Let me know if you want me to demo :)

2023-01-25 15:36 UTC, ChrisS1512 submitted a review, later dismissed

2023-01-25 15:38 UTC, KianKwa submitted a review, later dismissed

2023-01-30 14:29 UTC, ChrisS1512 approved these changes

2023-01-30 14:57 UTC, KianKwa approved these changes

2023-01-30 15:21 UTC, merged