PUB-1669 System Admin Audit Logs
hmcts/pip-frontend pull request #770
Opened 2023-02-02 14:10 UTC by joshblackmoor

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1669

### Change description

- Added new endpoint for sending system admin actions to be logged in the audit table
- Added new frontend screen within the system admin dashboard to view the audit logs.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-03 15:28 UTC, ChrisS1512 requested changes
Similar comment to the data tables one - we also need a log for the Delete Court one too

2023-02-06 12:07 UTC, joshblackmoor commented
> Similar comment to the data tables one - we also need a log for the Delete Court one too

Done :)

2023-02-06 12:23 UTC, ChrisS1512 submitted a review, later dismissed

2023-02-06 15:08 UTC, KianKwa approved these changes

2023-02-09 11:37 UTC, ChrisS1512 approved these changes

2023-02-09 11:40 UTC, KianKwa approved these changes

2023-02-09 11:41 UTC, merged