PUB-1896 Enhance audit log viewer
hmcts/pip-frontend pull request #829
Opened 2023-03-08 14:21 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1896

### Change description ###

Enhance audit log viewer

![image](https://user-images.githubusercontent.com/80688761/223737453-82dd9867-5c57-4376-a608-d76e2ec4a50f.png)

![image](https://user-images.githubusercontent.com/80688761/223737546-f18844e8-64c8-4943-bebd-2760ed5e3ce0.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-09 15:40 UTC, ChrisS1512 requested changes

2023-03-09 17:26 UTC, KianKwa commented on src/main/service/auditLogService.ts
> +                    html: `<a class="govuk-link" id="view-details-link" href="audit-log-details?id=${auditLog.id}&timestamp=${timestamp}">View</a>`,
Now the html is construction in the nunjuck file

2023-03-10 10:30 UTC, ChrisS1512 requested changes
Just conflict then happy to approve :)

2023-03-14 09:23 UTC, ChrisS1512 approved these changes

2023-03-14 09:42 UTC, furnivall submitted a review, later dismissed

2023-03-17 14:25 UTC, ChrisS1512 approved these changes

2023-03-17 14:28 UTC, furnivall approved these changes

2023-03-17 14:45 UTC, merged