PUB-1930 Beta survey feedback on B2C password reset returned pages
hmcts/pip-frontend pull request #871
Opened 2023-04-04 19:31 UTC by KianKwa

**Before creating a pull request make sure that:**

-   [ ] commit messages are meaningful and follow good commit message guidelines
-   [ ] README and other documentation has been updated / added (if needed)
-   [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1930

### Change description

Beta survey feedback on B2C password reset returned pages

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-12 09:44 UTC, joshblackmoor approved these changes

2023-04-13 09:15 UTC, ChrisS1512 requested changes
Looks great! Just needs E2E test adding as discussed

2023-04-13 14:27 UTC, ChrisS1512 approved these changes

2023-04-13 14:41 UTC, ChrisS1512 submitted a review, later dismissed

2023-04-13 14:42 UTC, joshblackmoor submitted a review, later dismissed

2023-04-19 14:26 UTC, ChrisS1512 approved these changes

2023-04-19 14:29 UTC, joshblackmoor approved these changes

2023-04-19 14:30 UTC, merged