Pub 1834 - E2E Test for User Management
hmcts/pip-frontend pull request #876
Opened 2023-04-14 15:18 UTC by ChrisS1512

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1834

### Change description

Added testing for the User Management page. 

Removed old tests which are now duplicated by this.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-18 14:04 UTC, ashwini-mv requested changes

2023-04-18 14:04 UTC, ashwini-mv commented on src/test/end-to-end/tests/system-admin/system-admin-user-management-test.ts
> +    I.see('This user has been updated to a CTSC Admin');
When the text is result of an action then first time we use I.waitForText
  I.click('Continue');
    I.see('User Updated');
    I.see('This user has been updated to a CTSC Admin');

2023-04-18 14:04 UTC, ashwini-mv commented on src/test/end-to-end/tests/custom-steps.ts
>  };
Is it possible to create and delete user through api call ?

2023-04-19 08:12 UTC, KianKwa commented on src/test/end-to-end/tests/system-admin/system-admin-user-management-test.ts
> +    I.click('.govuk-pagination__link');
Are we supposed to test "I.see('Next')" again after clicking the link?

2023-04-19 12:46 UTC, ChrisS1512 commented on src/test/end-to-end/functional.conf.ts
> +    tests: './tests/**/*-test.ts',
Good spot, updated

2023-04-19 12:48 UTC, KianKwa submitted a review, later dismissed

2023-04-19 13:32 UTC, ashwini-mv approved these changes

2023-04-21 09:54 UTC, KianKwa approved these changes

2023-04-21 14:27 UTC, ashwini-mv approved these changes

2023-04-21 14:29 UTC, merged