Pub 1999
hmcts/pip-frontend pull request #926
Opened 2023-05-18 13:55 UTC by NatashaAlker

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1999

### Change description

Display "LIST_ASSIST" rather than "SNL" as the Data Source when showing lists

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-23 14:21 UTC, joshblackmoor commented on src/main/modules/nunjucks/njkFilters.ts
> +        return provenance == 'SNL' ? 'LIST_ASSIST' : provenance;
Same comment as on other PR if it should be ListAssist or LIST_ASSIST :)

2023-05-23 14:22 UTC, joshblackmoor reviewed
Just wondering if we could add a test or two on one of the views to check that when its SNL it is successfully updated to the new name? Happy either way

2023-05-23 14:33 UTC, ChrisS1512 requested changes

2023-05-23 14:33 UTC, ChrisS1512 commented on src/main/controllers/CrownWarnedListController.ts
> +                provenance: metaData['provenance'],
I think this can be changed back to .provenance (It provides some type safety over the ['provenance'] version)

2023-05-25 16:09 UTC, ChrisS1512 approved these changes

2023-05-26 08:10 UTC, joshblackmoor approved these changes
Nice :) Happy first ticket on pip

2023-05-26 08:13 UTC, KianKwa approved these changes

2023-05-31 13:00 UTC, merged