PUB-1975 sorry list no longer available
hmcts/pip-frontend pull request #929
Opened 2023-05-24 08:16 UTC by joshblackmoor

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1975

### Change description

Added new sorry list no longer available page for scenarios where data management returns 404 for list meaning its expired or never existed.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-05-24 09:04 UTC, ChrisS1512 requested changes

2023-05-24 09:04 UTC, ChrisS1512 commented on src/main/controllers/DailyCauseListController.ts
> +        if (searchResults !== HttpStatusCode.NotFound && metaData !== HttpStatusCode.NotFound) {
I think we should also do a null check here to capture any 500 errors

2023-05-25 14:45 UTC, KianKwa approved these changes

2023-05-25 14:45 UTC, KianKwa submitted a review, later dismissed

2023-05-25 15:06 UTC, ChrisS1512 submitted a review, later dismissed

2023-05-31 16:55 UTC, KianKwa approved these changes

2023-06-01 08:18 UTC, NatashaAlker approved these changes

2023-06-01 08:19 UTC, merged