Setup communication front end and business rules
hmcts/pip-frontend pull request #93
Opened 2021-10-01 14:10 UTC by rabi-evoco

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-10-01 14:53 UTC, vialde approved these changes

2021-10-04 08:52 UTC, chris-pateman requested changes
need to make sure it is working and deployed

2021-10-04 08:52 UTC, chris-pateman commented on charts/pip-frontend/values.dev.template.yaml
> +  java:
You do not need the Java node

2021-10-04 08:52 UTC, chris-pateman commented on charts/pip-frontend/values.yaml
> +java:
You should not have the Java node here

2021-10-04 08:52 UTC, chris-pateman commented on charts/pip-frontend/values.yaml
> +   API_URL: pip-business-rules.{{ .Values.global.environment }}.platform.hmcts.net > sds-app.{{ .Values.global.environment }}.platform.net
You should not have everything after the '>' as it should just be a URL

2021-10-04 10:26 UTC, chris-pateman approved these changes

2021-10-05 15:27 UTC, merged