Pub 1839 manage media account request
hmcts/pip-frontend pull request #961
Opened 2023-06-06 09:41 UTC by ashwini-mv

### JIRA link

https://tools.hmcts.net/jira/browse/PUB-1839

### Change description

Added functional tests to manage media account request

```
[ ] Yes
[x] No
```

2023-06-09 08:13 UTC, joshblackmoor submitted a review, later dismissed

2023-06-09 08:26 UTC, ChrisS1512 requested changes
Can we remove the old E2E create account / media account request journey as part of this

2023-06-09 08:29 UTC, ashwini-mv commented
> Can we remove the old E2E create account / media account request journey as part of this

I will remove it :)

2023-06-09 15:35 UTC, ChrisS1512 approved these changes

2023-06-12 08:14 UTC, joshblackmoor approved these changes

2023-06-12 08:20 UTC, merged